### ISSUE TITLE
Add ability to specify skipping default values per class/property

### ISSUE THREAD

**Issue by varahash** [ngs-doo/dsl-json#105]
Introduce new property `serializingPolicy` to the following annotations `@CompiledJson` and `@JsonAttribute`.

```java
enum SerializingPolicy {
    // Uses DslJson.omitDefaults
    DEFAULT,
    
    // Omit default values from resulting json
    MINIMAL,

    // Serialize all properties
    FULL
}
```
By default `serializingPolicy = DEFAULT`

Example:
```java
// override policy for this particular class, so all properties in this class with default values will be omitted
@CompiledJson(serializingPolicy = MINIMAL) 
class User {
    // if null will be omitted
    public Long id; 

    // override policy for this particular property
    @JsonAttribute(serializingPolicy = FULL) 
    public String name; // will be serialized regardless is null or not
}
```

**Comment by varahash** [comment]
Alternative naming:
```java
enum OmitDefaultsPolicy {
    DEFAULT,
    ALWAYS,
    NEVER
}
@JsonAttribute(omitDefaults = ALWAYS)
@JsonAttribute(omitDefaults = NEVER)
```

**Comment by varahash** [comment]
It's little bit unclear to me how to correctly implement this.

Currently generated converter implements `FormatConverter`, so it looks like this:
```java
class ObjectFormatConverter implements FormatConverter<User> {
    public final void write(JsonWriter writer, User instance) {
        if (!__dsljson.omitDefaults) { writeContentFull(writer, instance); }
        else writeContentMinimal(writer, instance));
    }

    public void writeContentFull(JsonWriter writer, User instance) { ... }

    public boolean writeContentMinimal(JsonWriter writer, User instance) { ... }
}
```

Inside `writeContentFull` we always write all properties into JSON, inside `writeContentMinimal` we checks for default values.

Now consider we have following class, and try serialize it with `DslJson.Settings().skipDefaultValues(false)`:
```java
@CompiledJson(serializingPolicy = DEFAULT) 
class User {
    public Long id;
    @JsonAttribute(serializingPolicy = MINIMAL) 
    public String name;
}
```

Should we check `name` property inside `writeContentFull`? Or 'writeContentFull' should write all properties regardless  of `serializingPolicy` on property?

If we will perform checks inside `writeContentFull` and all properties on class marked with `serializingPolicy = MINIMAL`, then there will be no difference between `writeContentFull` and `writeContentMinimal` methods.

It seems `writeContentFull` and `writeContentMinimal` will not fit well into new paradigm where we can control omitting defaults values per class/property.


Maybe we need to introduce new abstraction:
```
class DslJson {
    boolean omitDefaults; // deprecate

    boolean ignoreSerializingPolicy;
    SerializingPolicy defaultSerializingPolicy;
}

interface FormatConverter<T> {
    void writeContent(JsonWriter writer, T instance, SerializingPolicy serializingPolicy /* or null to ignore */)
   
    // remove
    public void writeContentFull(JsonWriter writer, T instance)
    // remove
    public boolean writeContentMinimal(JsonWriter writer, T instance)
}
```
if `ignoreSerializingPolicy` then we will serialize all properties into JSON regardless defined policies on class/property.
Maybe we can remove `FormatConverter` completely.

**Comment by zapov** [comment]
We should avoid doing runtime checks whenever possible, meaning writeContent with policy argument (instead of current methods) is not a good fit.
We also can't really get rid of FormatConverter since it's use case is to write additional info not known to the class at that time.
Also, if you are writing properties conditionally, you need to have boolean as return type to know if anything at all was written.
Also, there is the array format, which always writes all properties, since it can't write them conditionally, and in the process lies about the writeContentMinimal signature, since it just redirects to full.

So... what we can do... we can look into after we know what use cases we want to support?
My main use case would be to be able to combine two classes... where one serializes everything and the other serializes stuff conditionally.

So from that perspective `serializePolicy` on the class would mean how to serialize it regardless of the global settings. In that sense maybe a better name on class annotation would be objectFormatPolicy = {DEFAULT, FULL, MINIMAL}

The other use case would be fine tune minimal serialization. Meaning we want to instruct serialization of some properties always, even when values are equal to default ones. A better annotation name in that case would be minimalSerializationPolicy = {ALWAYS_INCLUDE, OMIT_WHEN_DEFAULT} (hopefully with some better names)

Is there some other use case we would need to cover?

**Comment by varahash** [comment]
This makes more sense. One downside is that if you need to omit only one property from the class you will need to mark all other properties with 'ALWAYS_INCLUDE'.

Alternative names:
includeToMinimal = { ALWAYS, NON_DEFAULT } // we also can support NON_NULL

**Comment by zapov** [comment]
`includeToMinimal = { ALWAYS, NON_DEFAULT }` sounds good

The problem with NON_NULL is that it either needs to match the default or it should not be possible.
Otherwise you can't really deserialize it correctly.
