### ISSUE TITLE
Annotations do not take effect

### ISSUE THREAD

**Issue by baceto123** [ngs-doo/dsl-json#113]
Hi, 
I'm initializing DslJson with the following setup:
new DslJson<>(Settings.withRuntime().allowArrayFormat(true).skipDefaultValues(true).includeServiceLoader());

In my class I have the following property:

@JsonAttribute(includeToMinimal = IncludePolicy.ALWAYS)
public int o;

I'm deliberately leaving the property with its default value. The property does not get included in the json output, but it should.

Also tested other annotations and none take effect. Here's my best guess what might be the problem:
* I'm initializing with Settings.withRuntime()
* I saw the JsonAttribute source and the interface has @Retention(RetentionPolicy.CLASS)
* I guess the runtime can't read the annotation, because it's not compiled with RetentionPolicy.RUNTIME?

**Comment by zapov** [comment]
Do you have `@CompiledJson` on your class?

It reads annotation during compile time, it does not need it in runtime.

**Comment by baceto123** [comment]
No, didn't have @CompiledJson on the class, but adding it does not make a difference.

**Comment by zapov** [comment]
I can only guess that there is something wrong with your setup, eg, annotation processor not running.

It would help if you can show some code, make a failing test, otherwise it will be a guessing game.

Here are the test which shows that the feature is working: https://github.com/ngs-doo/dsl-json/blob/7f06827328be937b2f1798683078092f847f78ff/tests-java8/src/test/java/com/dslplatform/json/ObjectFormatPolicyTest.java

If you are using gradle, you might have not specified apt/annotationProcessor to run on the java8 project.

Can you try writing your code in one of existing example projects, eg Maven8. This will help narrow the problem to your setup or to actual problem in the library.

btw. Settings.withRuntime() should not be required most of the time. If you don't include that in initialization and dsl-json fails to run, this will show you that annotation processor is not running. In a way dsl-json will fallback to reflection with that setting enabled, so it will be confusing to determine what the actual problem is unless you have some experience with the library.

**Comment by baceto123** [comment]
Yes, there was something wrong with my pom.xml and the annotation processor was not running. I've recreated the file and now it's OK.

But I found another issue with default float values. They always get included in the output json.
The property is:

public float j;

I'm setting it to j = 0; and the final json always contains {"j":0.0}
int and String default properties in the same class do not get included as expected.

**Comment by zapov** [comment]
If you can add PR with such test it would be great.

**Comment by zapov** [comment]
Just for sanity check I added test for float in last commit: https://github.com/ngs-doo/dsl-json/commit/0840300112cf5f6fe8c4cedf8f4b60710ab629d0

I think this always behaved as expected.

**Comment by zapov** [comment]
v1.9.0 released
If you managed to reproduce the problem, please provide a test case and/or reopen the issue
