### ISSUE TITLE
java.io.IOException when deserialising to class

### ISSUE THREAD

**Issue by emrul** [ngs-doo/dsl-json#114]
Hi,

I'm using Kotlin 1.3 and have a rather simple setup that's not working:
```
@CompiledJson
data class GraphQLRequest(val id: String? = null, val query: String = "", val variables: Map<String,Any> = emptyMap(), val operationName: String? = null)

val dslJson = DslJson<Any>(Settings.withRuntime<Any>().includeServiceLoader())

val jsonInputStream = "{\"query\":\"mutation T(\$input: [DocumentInput]) {createDocument(input: \$input) {name,id}}\",\"variables\":{\"input\":[{\"name\":\"doc1\"},{\"name\":\"doc2\"}]},\"operationName\":\"T\"}".byteInputStream(Charsets.UTF_8)
//val mapVal = dslJson.deserialize(Map::class.java, jsonInputStream)
val gqlRequestVal = dslJson.deserialize(GraphQLRequest::class.java, jsonInputStream)

```

Deserialising to a Map (the commented mapVal line works) but deserialising to GraphQLRequest (as in the last line) results in: ```java.io.IOException: Expecting '}' at position: 3, following: `{"q`, before: `uery":"mutation T($i`. Found q```

I'm sure I've done something wrong but I can't figure out what, any pointers would be really helpful.

**Comment by zapov** [comment]
Hi

So many unrelated problems at such small piece of code ;(

One is that while building such a class you get compile warning:  `w: warning: No properties found on: 'GraphQLRequest'. Since it's not used as implementation for some mixin, it's most likely an invalid class configuration (name mismatch, missing setter, etc...)`

This seems due to analysis not coping with both ctors on the class. It should certainly be improved so it knows how to do that.

The other problem is that I don't think analysis understand Kotlin defaults (and custom defaults are on TODO anyway ;( )
So if defaults are just nulls and empty objects, DSL-JSON should register empty strings and empty maps there, but it doesn't seem to be doing that ;(

Also, DSL-JSON doesn't like the use of Any/Object as property by default. But I'm not really fluent with Gradle/Kotlin so don't know how to turn it into a warning by specifying compilerArgument `Adsljson.unknown=WARNING`
I'm not sure you can even do it the expected way, by setting converter which overrides the warning:

    @JsonAttribute(converter = com.dslplatform.json.runtime.MapAnalyzer.Runtime::class.java)

Also, due to failure to pick up the properties, it seems that code generated for empty class does not cope with input (but it should - thats the error you have pasted)

I was able to make it work by changing the signature of a map into `Map<String,List<Map<String,String>>>` and by removing default from one of the properties (which in turn removed the default ctor)

So, all in all, there seems to be multiple issues here and it would be nice if some Kotlin person helps with some of them. I'll probably have some time next week to look into more closely/fix some of those.

**Comment by emrul** [comment]
Thanks for the thorough response.  I'll see if in the next week I can help improve the annotation handling for Kotlin.

**Comment by codeaze** [comment]
Just wanted to add a comment to this issue, that, in my opinion, having IOException when deserialization fails is not very appropriate. While deserializing data from remote web service, it is not easy to distinguish between the cases of connection failure and deserialization error, since both throw an IOException.
It would be nice if you're able to change it and have some kind of DslDeserializationException.

**Comment by zapov** [comment]
I agree. It was one of the early decisions which is not easily changed at this point as I think it would be best to have a runtime exception for that.
But we should certainly introduce a ParsingException (which can inherit from IOException) and thus keep the signature

**Comment by zapov** [comment]
@emrul some of the issues are fixed for v1.9.0 which now has better support for defaults. Your use case should be working now. If you wish to test please build locally and get back. There are still some thing to fix (case when there are no properties, but thats a minor thing)

@codeaze with commit https://github.com/ngs-doo/dsl-json/commit/8c67016c8fc8918aba4c3833fb71b7b359b3f2ec there is now ParsingException which is thrown instead of IOException. I actually wanted to use it on more places, but @hkratz suggested to use EOFException in some specific cases.
I'm interested to hear what others (@varahash ,...) think about that, as I'm currently leaning towards using ParsingException with a nested EOFException, although I don't mind all that much having just EOFException for case when there should be more JSON to read

**Comment by emrul** [comment]
Thanks @zapov , I will try - I was using Jsoniter but wanted to explore other options.

Separate question: Does DSL JSON have anything like lazy parsing? In many cases we're passing Json straight through with only minimal inspection of objects?

**Comment by plokhotnyuk** [comment]
When exception is getting to be non exceptional, e. g. in case of malicious input, it can consume much more CPU cycles than during parsing of valid message.

Please consider adding a configurable option to throw parsing exception without stack traces.

Look for more info in [this amazing article](https://shipilev.net/blog/2014/exceptional-performance/).

**Comment by zapov** [comment]
Very good suggestion @plokhotnyuk . I agree it's worth having configuration option for that.

@emrul not sure what you mean by lazy parsing. By default JSON is parsed in a way that it skips over the parts which do not match the schema (you can control that behavior). In that sense it could be considered lazy parsing, although I never named it like that since you can't retry it, nor the binding is done lazily.

**Comment by zapov** [comment]
@plokhotnyuk I did some work around that in the last commit. If you have some setup for benchmarking it I would love to see the result.
@hkratz I've changed your PR so dsl-json now throw only it's own specific exceptions, but it will put EOF exception as inner one in cases you were interested in

I still have to look into the last issue (class with no properties) which I hope will look into this week

**Comment by plokhotnyuk** [comment]
@zapov do you have proven to work steps how to build and publish locally all artifacts for the latest snapshot of DSL-JSON?

**Comment by zapov** [comment]
For Java I do

    mvn clean install

Then for Scala

    sbt +publishLocal

I know it would be better to use -SNAPSHOT in the name between the releases ;(

**Comment by plokhotnyuk** [comment]
I which files the `-SNAPSHOT` suffix should be added to avoid publishing invalid artifacts?

**Comment by zapov** [comment]
Well,... +publishSigned only deploys the artifacts to Maven so I'm not afraid of accidental publishing as it requires additional approval.
It's mostly for being able to reupload stuff into Maven and working around SBT refusal to overwrite locally published stuff.
So for now I try to keep it with as minimal overhead for me as possible. But I don't mind all that bureaucracy [as long as I don't have to deal with it ;( ]

**Comment by plokhotnyuk** [comment]
I'm asking about local publishing: to build DSL-JSON artifacts and publish them locally in maven and ivy cashes...

**Comment by zapov** [comment]
Let's continue that on your scala 2.13 thread. Past the log and I might know whats going on

**Comment by zapov** [comment]
v1.9.0 released
All relevant issues have been fixed
