### ISSUE TITLE
Cannot create decoder for simple Scala case class

### ISSUE THREAD

**Issue by plokhotnyuk** [ngs-doo/dsl-json#126]
The following code throws `java.lang.IllegalArgumentException: requirement failed: Unable to create decoder for XS`:

```
import com.dslplatform.json.{DslJson, DslJsonScala}

case class XS(xs: IndexedSeq[Int])

new DslJsonScala(new DslJson[Any](new DslJson.Settings[Any]())).decoder[XS]
```

**Comment by zapov** [comment]
You need to enable runtime conversion for Scala ;(
Service loader should pick up signatures, but you can explicitly register them as:

    val dslJson = new DslJson[Any](Settings.withRuntime().`with`(new ConfigureScala))

**Comment by zapov** [comment]
btw. to clarify the comment, `Settings.withRuntime` is for Java signatures, while `new ConfigureScala` is for Scala signatures.
So just new DslJson[Any]() should work by default since it should pick up ConfigureScala using service loader. I'm wondering what setup are you using for this not to work. Graal or something?
