### ISSUE TITLE
Proposal: change your license type to Apache

### ISSUE THREAD

**Issue by cogito-clarus** [ngs-doo/dsl-json#141]
Most companies that range from mid-size (hundreds of employees) to "Fortune 10" (tens of thousands of employees) have legal departments that insist on a well known and permissive license to open source software.  While your license is permissive, lawyers hate deviating from the "well known".  Although unfair and illogical, my org won't bless this software for usage in our services for this exact reason.

**Comment by zapov** [comment]
Current license is BSD-3 (and for some reason Github stopped recognizing it as such - I'll have to look into why)
The main difference is that there is no explicit patent reference in BSD, but while I know that lawyers prefer Apache over BSD I must admit I have not yet heard that vanilla BSD-3 was rejected at such companies.

So are you saying that BSD-3 is not good enough, or that we should fix text so that Github recognizes license as BSD-3?

**Comment by zapov** [comment]
The license is BSD-3 and it won't be changed to Apache
