### ISSUE TITLE
ByteArray deserialization

### ISSUE THREAD

**Issue by markebbers** [ngs-doo/dsl-json#204]
I have a large model with a lot of Strings. These Strings are UTF8 encoded and I will store them the same way. So I'm looking for a way to deserialize these Strings directly to ByteArray (for the best performance). Defining these as ByteArray in the models does not work. 

I also created a custom UTF8String & UTF8StringConverter but this is a lot slower then just parse the strings.

**Comment by zapov** [comment]
"By defining them as ByteArray it does not work", you mean that they are not supported by default? Because you can always register custom type/converter.

Direct String -> byte[] conversion is not always possible, since sometimes conversions are required.

There is StringCache interface which you could use to avoid string allocations, but I always find it slower than vanilla implementations. I guess its highly project dependent.

You can also redirect String conversion via JsonConverter and performance of that should be only bound to the actual implementation, but you will be able to access raw bytes that way instead of using this char[] api from StringCache.

**Comment by markebbers** [comment]
> "By defining them as ByteArray it does not work", you mean that they are not supported by default? Because you can always register custom type/converter.

By default this is indeed not supported, but I implemented a custom converter, annotated the field, but the annotation-processor looks like to have some problems with this approach. I implemented a simple string->byte[] converter to test with

```kotlin
@CompiledJson(onUnknown = CompiledJson.Behavior.IGNORE)
class Article {
    @JsonAttribute(converter = ByteArrayConverter::class)
    var name: ByteArray? = null
}

object ByteArrayConverter {

    val JSON_READER = object : JsonReader.ReadObject<ByteArray?> {
        override fun read(reader: JsonReader<Any>): ByteArray? {
           return reader.readString().toByteArray()
        }
    }
    val JSON_WRITER = object : JsonWriter.WriteObject<UTF8String?> {
        override fun write(writer: JsonWriter, value: UTF8String?) {
            TODO("Not yet implemented")
        }
    }
}
```

But the annotation-processor throws a nullpointer
```
Caused by: java.lang.NullPointerException
	at com.dslplatform.json.processor.Analysis.validateConverter(Analysis.java:685)
	at com.dslplatform.json.processor.Analysis.analyzeAttribute(Analysis.java:923)
	at com.dslplatform.json.processor.Analysis.findRelatedReferences(Analysis.java:843)
	at com.dslplatform.json.processor.Analysis.processAnnotation(Analysis.java:161)
```

Which traces back to
```java
		String allowed = onlyBasicFeatures ? "field" : "field/method";
		if (!converter.getModifiers().contains(Modifier.PUBLIC)) {
			hasError = true;
			messager.printMessage(
					Diagnostic.Kind.ERROR,
					"Specified converter: '" + converter.asType() + "' must be public",
					converter,
					getAnnotation(converter, converterType));
		} else if (!target.getModifiers().contains(Modifier.PUBLIC)) { // THIS LINE FAILES
			hasError = true;
			messager.printMessage(
					Diagnostic.Kind.ERROR,
					"Specified converter target: '" + fullName + "' must be public",
					converter,
					getAnnotation(converter, converterType));
```
Maybe something to do with Kotlin or the ByteArray class?

**Comment by zapov** [comment]
Tnx for detailed info. 
I just fixed this NPE in Analysis in latest commit. It should point now to actual problem in your converter (different types).

Yeah, the built-in string parser is highly optimized so its hard to beat.
Also, if your code uses more than one thread, this implementation is likely to break due to reuse of buffer singleton.

Not sure if this is the implementation you benched, as it looks to me that it allocates utf string and empty byte array of 1 at the end and it does not copy read elements at all.

I'm guessing there is some hotspot optimizations kicking in when strings are "normally" created which avoids allocations happening when non string types are used.

**Comment by markebbers** [comment]
> Not sure if this is the implementation you benched, as it looks to me that it allocates utf string and empty byte array of 1 at the end and it does not copy read elements at all.

You can ignore that, I was testing the difference between a empty array and copying the bytes from the buffer.

**Comment by zapov** [comment]
v1.9.8 released
