### ISSUE TITLE
Need support snake case without @JsonAttribute 

### ISSUE THREAD

**Issue by longdt** [ngs-doo/dsl-json#208]
As title, I need a way to setting dsl-json uses snake-case without @JsonAttribute annotation.
Maybe we can use @CompiledJson(namingStrategy = Case.SNAKE_CASE)

**Comment by zapov** [comment]
I guess it would be nice if instead of `minified()` on CompiledJson there is something like namingStrategy, although certainly not built in via enumeration like this, but rather by referencing a class which implements the expected behavior.
I can look into refactoring current minified naming strategy into such pattern, but don't really have a need to implement other strategies like snake casing.
If someone is interested in contributing some other naming strategy let me know and I'll look into setting up infrastructure for it.

**Comment by longdt** [comment]
Yes, I think we can refactor `minified()` to support other strategies. I hope I can contribute but I'm busy with company projects.
P/s I'm a big fan of dsl-json, your library is amazing. I like idea: using annotation processor to generate source code

**Comment by zapov** [comment]
I pushed this change with latest commit

**Comment by longdt** [comment]
thanks

**Comment by zapov** [comment]
v1.9.9 released
