### ISSUE TITLE
Add support for multi module projects

### ISSUE THREAD

**Issue by varahash** [ngs-doo/dsl-json#60]
**Problem**:
Consider multi module project, consists of 'app' and 'lib1' modules, where 'app' module depends on 'lib1'. Each module has POJO classes which annotated with 'CompiledJson'. When we compile 'app' module, the 'dsl_json_Annotation_Processor_External_Serialization' is generated by annotation processor at the top level. But the same file also generated for 'lib1' module. As result we are unable to use generated code from 'lib1' module because, there is class collision.

**Solution**:
I propose to generate converters for each POJO class, instead of single fat 'dsl_json_Annotation_Processor_External_Serialization' class.
For example if we have 'User' class inside 'com.example.app' package, then generate 'User_dslJsonConverter' class inside same package and register it into 'META-INF/services/com.dslplatform.json.CompiledJson'

**Comment by zapov** [comment]
Gen classes sometimes call directly one into another, so we would need to change visibility to public on most stuff.

The DSL annotation processor supports custom namespace via `dsljson.namespace`. It seems easier to add that configuration to Java8 which would resolve the collision problem?

**Comment by zapov** [comment]
Also, keep in mind that processor will create converters in parent project even for objects in dependent projects if they are referenced from the parent project. I'm not sure if it will create them in they just have annotation, but are not referenced. Something to check...

**Comment by varahash** [comment]
Yes, custom namespace can fix collision problem, but it looks like workaround. Also there is same problem with unit test, if we try to use 'CompiledJson' inside unit tests, the test gen class will override main gen class, so namespace does not help here. (Actually, we can also introduce separate namespaces for the unit test target, but it's even worse)
Splitting out gen file into separate small files, also help to optimize incremental build. Currently, if looking into 'tests-java8' module, gen class for 50 POJO classes takes for around 6K lines of code in single file.
Does annotation processor generate code in parent project for objects in dependent projects, even after loading ''META-INF/services/com.dslplatform.json.CompiledJson' from dependent projects? I guess, if a object type is loaded from META-INF configuration, then annotation processor should not generate code for such object type.

**Comment by zapov** [comment]
The main reason I prefer this fat classes is that they are used as a workaround on some platforms (Android, Kotlin) which don't have proper META-INF support. So DSL-JSON just tries to load some of those again if it was expecting to fine something but it didn't find anything.

That said, yes, your proposal seems good and will solve several issues with multi project setups.
So I welcome such changes, but they need to be a configuration option on the processor ;( Not sure if there is a better way to go about that.

Annotation processor should not create codecs for stuff which it already knows how to process, so that should work as expected (except that the new file can conflict/overwrite the one it used during analysis).

**Comment by varahash** [comment]
There was problem with META-INF on Android platform caused by build tools, but it was fixed 2 years ago (https://issuetracker.google.com/issues/36978763). I've just verified examples AndroidJava6, and AndroidKotlin on devices with android versions 4.1 and 8.1. And I can confirm ServiceLoader.load works as expected. (FYI: android examples has issues, so build fails)
Also we can add new fallback, when object type is unknown, then just verify that there is exist class converter for that type. It easy to do because each type will have converter alongside with it. e.g. Class 'com.example.app.User' will have 'com.example.app.User_dslJsonConverter'
Is there are any other reasons to keep using a fat file?

**Comment by zapov** [comment]
The remaining issues which come to mind are:

 * compilation dependency - so all classes/codecs are known at compile time. You can do this currently by initializing DSL-JSON with explicit converter, so that stuff like Graal work and there is no runtime loading of classes
 * sealed packages
 * extra visible objects - which might annoy people if they are public and popping up in autocomplete - but it doesn't seems like a major thing/blocker. We can also trivially fix this by putting it into some specific package, eg... dsl_json.package.Class_DslJsonConverter

But we can just register converters into the "fat" file for all known codecs (coupled with custom namespace - this would solve main remaining problems I see)
Not sure about sealed packages... something to look into.

So I agree that it makes sense to spread converters along classes whenever possible (which will work out of the box if that naming convention is followed for loading codecs). And I'm fine with having "fat" converter which aggregates all known classes into a single registration becomes a configuration option (not on by default)

**Comment by varahash** [comment]
Ok, so if package is sealed then put converter implementation into 'dsl_json.package.Class_DslJsonConverter' package, if not then use original class package. 
Also using original class package allows us to generate code for package-private POJO classes and properties;)

For extra visible objects problem there are two options:
- configure IDE to exclude such objects from autocompletion (e.g https://www.jetbrains.com/help/idea/auto-completing-code.html#configure-code-completion )
- use prefix "_" for class converter (e.g 'package._Class_DslJsonConverter'). Putting converters into some specific package does not solve this problem, because IDE is smart enough to find them:)

I can provide PR for this. 
How to name new configuration option, which responsible for generating 'fat' configuration?
Is '_DslJsonConverter' suffix appropriate for generated file? because actually it would implement 'com.dslplatform.json.Configuration'

**Comment by zapov** [comment]
Prefix sounds good. 
I guess we can request full path to configuration name, eg: `dsljson.configuration` with argument such as `com.package.MyProjectDslConfig`
Converter or Codec conveys the meaning of that class much better. Configuration is a generic name for setting up DslJson. I wouldn't even implement Configuration on such _DslJsonConverter classes and would not register them in META-INF. Instead every time a unknown class is requested I would probe those specific places instead [as long as config for that was specified, eg includeServiceLoader() ]

Looking forward to you PR
