### ISSUE TITLE
POJO properties annotated as nonnull should be mandatory by default

### ISSUE THREAD

**Issue by varahash** [ngs-doo/dsl-json#64]
Currently if a json missing some attribute, the 'null' will be assign to POJO property. But this no make sense if property is annotated as nonnull. We should throw exception instead.

**Comment by zapov** [comment]
Well, there is a distinction, although it might not be fully done yet in Java8 version.

Default for nonnull String is empty string. Meaning if it's missing from input it will be an empty value.
Mandatory is a different thing from non-null.

**Comment by varahash** [comment]
OK, for simple types such as numbers, strings and booleans some empty value can be used. But what about more complex cases, for example: dates, enums, objects?
My main point is to prevent nulls in nonnull field after deserializing json into POJO instance.

**Comment by zapov** [comment]
Most types can have sane default. Specific enum values, object instances with default values, ....
It's rather rare for a type not to have a sane default eg XML, and maybe date in JVM.

Anyway, this issue is almost fine, but I'll rename it to be correct.
I need to enable defining custom type defaults (you can currently register them, but they wont get used in the processor), or custom defaults per property.

So mandatory is orthogonal to non-null (it just checks if a property exists in JSON), but yeah, it makes sense that if a type nor the property have a default value, but it's mandatory and non-null that it throws an exception at the end if property was null at the end of deserialization (I think the dsl processor already does something like that, but it needs to be ported to Java8 version)

**Comment by zapov** [comment]
With latest commit: https://github.com/ngs-doo/dsl-json/commit/79ebfd330732483799889c9c720f9c08e021f3de
library will now consider properties which are not nullable but don't have a default as mandatory.
I still need to introduce custom defaults per property, but thats a separate thing.

**Comment by zapov** [comment]
v1.9.2 released
