### ISSUE TITLE
Mark public api with nullability annotations 

### ISSUE THREAD

**Issue by varahash** [ngs-doo/dsl-json#68]
We can use [Jsr305](https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305/3.0.2) as base

Create custom NonNullApi annotation, which makes all parameters and return values non-nullable by default, e.g.
```
@Target(ElementType.PACKAGE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Nonnull
@TypeQualifierDefault({ElementType.METHOD, ElementType.PARAMETER})
public @interface NonNullApi {
}
```

then annotate package with it:
```
// file package-info.java
@NonNullApi
package com.dslplatform.json;
```

then annotate only nullable parameters or return values
```
import javax.annotation.Nullable;

public class DslJson<TContext> {
    @Nullable
    public JsonWriter.WriteObject<?> tryFindWriter(final Type manifest) {
    }
}
```

**Comment by zapov** [comment]
I would like to avoid taking external dependencies on the core project. I don't mind doing it from other projects.

**Comment by varahash** [comment]
There are two benefits doing so: 1) the IDEA will warn user when he missed null if-check, 2) when using lib with Kotlin, the api will be correctly translated to nullable types.
So adding nullable annotations dependency is not big evil, also I want to notice that this dependency will be of 'provided' scope.

**Comment by zapov** [comment]
Provided does sounds bearable, but I wonder how can it be of provided scope if it has runtime retention?

**Comment by zapov** [comment]
Ok, that sounds good

**Comment by varahash** [comment]
What is the best package for nullable annotations? Here few ones:
com.dslplatform.json
com.dslplatform.json.annotations
com.dslplatform.annotations
com.dslplatform.lang

**Comment by zapov** [comment]
The other annotations are in `com.dslplatform.json` so I would put them there. What also makes sense to me is to put them in something like `com.dslplatform.json.checks`.

**Comment by zapov** [comment]
I wanted to release v1.8.0 but Java 1.6 compiler fails to build all non library projects which don't have explicit findbugs dependency ;(

    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>jsr305</artifactId>
      <version>3.0.2</version>
      <scope>provided</scope>
    </dependency>

Is there some easy workaround for that? I could build them via Java8 compiler instead of Java6 one, but I've seen all kind of strange errors when I did that ;(

Is this due to package-info.java ? Do we really need it there? I don't see it used anywhere... but maybe since it's all non-null.

Also, I keep seeing errors in IntelliJ such as:

[warn] While parsing annotations in ...\dsl-json-1.8.0.jar(com/dslplatform/json/Nullable.class), could not find MAYBE in enum <none>.
[warn] This is likely due to an implementation restriction: an annotation argument cannot refer to a member of the annotated class (SI-7014).

**Comment by zapov** [comment]
It's seems it's a problem with Javac v1.6 ;(
I've build them via v1.8
Hopefully there won't be any related issues due to this...
