### ISSUE TITLE
Prettifying JSON

### ISSUE THREAD

**Issue by zapov** [ngs-doo/dsl-json#77]
Allow JSON output to be somewhat formatted.
Whats probably wanted is converter which will process the JSON input and output it in a formatted way.
This way it's totally separated from standard output logic.
Any performance overhead is probably not important anyway.

Main use case is to be able to totally deprecate other currently used libraries

**Comment by varahash** [comment]
Also we can make com.dslplatform.json.JsonWriter as interface, and have two implementations DefaultJsonWriter and PrettifyJsonWriter. Inside json writer we can parse inputed strings/bytes and track indention. 
Pros: All existing converters will work out of box. 
Cons: Performance will not be great, since we need parse raw json (but it simple, we need only track open/closed brackets and quotes).

**Comment by zapov** [comment]
I would like to keep it as a final class to simplify the escape analysis on it.
Prettyifing stream wrapper currently looks like the best option to me.

**Comment by zapov** [comment]
Fixed in v1.8.1
