### ISSUE TITLE
DslJson do not lookup external converter for generic class when Settings.withRuntime() used

### ISSUE THREAD

**Issue by varahash** [ngs-doo/dsl-json#89]
If we enable runtime analizers, in particular ObjectAnalyzer and ImmutabelAnalyzer, these converters are used before lookup external converters for parameterized types. See https://github.com/ngs-doo/dsl-json/blob/master/library/src/main/java/com/dslplatform/json/DslJson.java#L1031

**Comment by varahash** [comment]
We have two conflict cases:
1) User register custom factory 
2) User enabled runtime analyzers

In first case we need lookup factories before external converter
In second case we need lookup external converter before factories (to avoid running ObjectAnalyzer/Immutable analyzers)

It seems that we need to divide factories into two categories: high priority and low priority. So we will lookup high priority factories, then lookup external converters and then lookup low priority factories.

A user registered factories fall into high priority factory category, and ObjectAnalyzer/ImmutableAnalyzers fall into low priority factory category.

**Comment by zapov** [comment]
Yeah, I was looking at that a bit. There is also a case where you register your own factory for a type, but unless you do it in a specific way it will use the externally probed factory.

Currently the runtime analyzers are always the last to probe.... so that should not cause problems most of the time.

It looks like the order of registration should matter, but we have to do some acrobatics to support the order of user registered custom factory which conflicts with built in factory

**Comment by zapov** [comment]
Currently I'm inclined to just enable loading of external convention based stuff before the registered factories.

If someone wishes to fine tune this, he can register DslJsonConverter instead of factory to get the precedence.
Ideally we could support registration order and maintain two lists as you suggested, but doesn't seems as important right now to me.

What are your thoughts on the matter?

**Comment by zapov** [comment]
Pushed a commit which makes things more consistent. Let me know what you think

**Comment by varahash** [comment]
I like it. I thought to suggest same approach:)
